### ISSUE TITLE
FYI: DSN has this natively

### ISSUE THREAD

**Issue by akrigline** [gsimon2/dramatic-rolls#5]
As of DSN 3.3.0, you can create this kind of effect and sound directly within Dice So Nice settings:

https://gitlab.com/riccisi/foundryvtt-dice-so-nice/-/wikis/Special-Effects

I'm not sure this module shouldn't exist, but disabling it if DSN is active might not be a bad idea.

**Comment by gsimon2** [comment]
Nice! I did not know that Dice So Nice had released that feature. Very exciting.

Since it is easy for users to enable / disable modules on their own (as well as turn this module off in the settings menu), I plan on leaving this module as is, in respects to playing along with Dice So Nice's older versions. 

Thanks for posting!

**Comment by gsimon2** [comment]
I also updated the readme and foundry description to reflect that Dice So Nice has this built it.
